openapi: "3.0.0"
info:
  description: "Skeleton Service for creating models and API interface for rest ws to give to clients"
  version: "0.0.1"
  title: "Model Service Skeleton API"
  contact:
    email: "tinashehondo@gmail.com"
tags:
  - name: "user"
    description: "User - dummy tag to initialise service"
#servers:
#  - url: http://localhost:8000/
#    description: "local host"

paths:


  #get email by reference ID
  /notifications/email/{reference}:
    get:
      description: Get an email by reference ID
      operationId: getEmailByReference
      parameters:
        - name: reference
          in: path
          description: email reference ID
          required: true
          schema:
            type: integer
            format: int64
      tags:
        - notificationService
        requestBody:
          content:
            application/json:
              schema:
                $ref: ./message.yml#/Message
          description:  Get emails by reference
          required: true
      responses:
        200:
          description: The Message Response object with email details
          content:
            application/json:
              schema:
                $ref: ./message-response.yml#/MessageResponse
        400:
          description: HTTP 400 Failed to send SMS
          content:
            application/json:
              schema:
                $ref: ./errors/problem.yml#/Problem
        401:
          description: Unauthorized - The request requires user authentication
        403:
          description: Forbidden - The server understood the request, but is refusing it or
            the access is not allowed.
        404:
          description: Resource not found
        500:
          description: HTTP 500 Error Response
          content:
            application/json:
              schema:
                $ref: ./errors/problem.yml#/Problem